import { NextResponse } from "next/server";
import { createAdminClient } from "@/lib/supabase/admin";
import { getServerEnv } from "@/lib/env";
import { requireStaff } from "@/lib/require-admin";

export const runtime = "nodejs";

/**
 * Staff-only diagnostic for the contact form -> admin panel pipeline.
 *
 *   GET /api/admin/contact-diagnostics
 *
 * Reports, straight from the live (hosted) Supabase database:
 *   1. Whether the `contact_messages` table exists and how many rows it holds
 *      (this is exactly what the Admin Panel's Messages tab reads).
 *   2. The 5 most recent messages.
 *   3. An end-to-end anonymous write test identical to `/api/contact`
 *      (same anon key + RLS path). The test row is deleted immediately
 *      afterwards, so it is self-cleaning.
 *
 * If `anonymousWriteTest.ok` is false, the error there explains why public
 * contact-form submissions fail (e.g. missing anonymous-INSERT RLS policy,
 * missing table, missing message_status enum) — fix the database with the
 * `supabase/fix_contact_messages.sql` repair script.
 */
export async function GET() {
  try {
    const denied = await requireStaff();
    if (denied) {
      return NextResponse.json({ error: denied.error }, { status: denied.status });
    }

    const supabase = createAdminClient();
    const { NEXT_PUBLIC_SUPABASE_URL, NEXT_PUBLIC_SUPABASE_ANON_KEY } =
      getServerEnv();

    // --- 1) Table existence + message count (service role -> bypasses RLS) ---
    let tableExists = false;
    let messageCount = 0;
    let countError: string | null = null;
    try {
      const { count, error } = await supabase
        .from("contact_messages")
        .select("*", { count: "exact", head: true });
      if (error) throw error;
      tableExists = true;
      messageCount = count || 0;
    } catch (err: any) {
      countError = err?.message || String(err);
    }

    // --- 2) Latest messages exactly as the Admin Panel maps them ---
    let latest: any[] = [];
    let latestError: string | null = null;
    if (tableExists) {
      try {
        const { data, error } = await supabase
          .from("contact_messages")
          .select("*")
          .order("created_at", { ascending: false })
          .limit(5);
        if (error) throw error;
        latest = data || [];
      } catch (err: any) {
        latestError = err?.message || String(err);
      }
    }

    // --- 3) End-to-end anonymous write test (mirrors /api/contact) ---
    // Uses the anon key through the REST API exactly like the contact form.
    // The inserted row is deleted right away via the service-role client.
    let anonWrite: Record<string, unknown> = { attempted: false };
    if (tableExists) {
      const testRow = {
        name: "__connectivity_test__",
        email: "connectivity@nextsolution.local",
        phone: "",
        subject: "Connectivity test",
        message:
          "Automated diagnostics write test generated by /api/admin/contact-diagnostics. Safe to delete.",
        service: "Diagnostics",
        budget: "",
        status: "unread",
      };

      try {
        const res = await fetch(
          `${NEXT_PUBLIC_SUPABASE_URL}/rest/v1/contact_messages`,
          {
            method: "POST",
            headers: {
              apikey: NEXT_PUBLIC_SUPABASE_ANON_KEY,
              Authorization: `Bearer ${NEXT_PUBLIC_SUPABASE_ANON_KEY}`,
              "Content-Type": "application/json",
              Prefer: "return=representation",
            },
            body: JSON.stringify([testRow]),
          },
        );

        const body = await res.json().catch(() => ({}));

        if (res.ok && Array.isArray(body) && body.length > 0) {
          const insertedId = body[0]?.id;
          anonWrite = { attempted: true, ok: true, insertedId };

          // Clean up the test row with the service-role client.
          try {
            const { error } = await supabase
              .from("contact_messages")
              .delete()
              .eq("id", insertedId);
            anonWrite.cleanedUp = !error;
            if (error) anonWrite.cleanupError = error.message;
          } catch (err: any) {
            anonWrite.cleanupError = err?.message || String(err);
          }
        } else {
          anonWrite = {
            attempted: true,
            ok: false,
            status: res.status,
            error: body?.message || body?.error || `HTTP ${res.status}`,
            code: body?.code,
            details: body?.details,
            hint: body?.hint,
          };
        }
      } catch (err: any) {
        anonWrite = { attempted: true, ok: false, error: err?.message || String(err) };
      }
    } else {
      anonWrite = {
        attempted: false,
        ok: false,
        error: "Skipped — contact_messages table does not exist.",
      };
    }

    return NextResponse.json({
      ok: tableExists && anonWrite.ok === true,
      contact_messages: {
        tableExists,
        messageCount,
        countError,
        latest,
        latestError,
      },
      anonymousWriteTest: anonWrite,
      checkedAt: new Date().toISOString(),
    });
  } catch (error: any) {
    return NextResponse.json(
      { error: error.message || "Diagnostics failed." },
      { status: 500 },
    );
  }
}